title: Midnight theme
description: Midnight is a theme for GitHub Pages.
show_downloads: true
logo: /assets/img/logo.png
google_analytics: UA-277893315-1
theme: jekyll-theme-midnight
theme: jekyll-theme-cayman
theme: jekyll-theme-minimal
